### ISSUE TITLE
放大缩小功能

### ISSUE THREAD

**Issue by 1063573718** [ssthouse/vue-tree-chart#10]
作者您好，项目需要，github上搜寻到您开发的vue-tree-chart插件，使用Svg版本没问题，但是项目应用中会需要像您这个demo中鼠标滚动放大缩小功能，我尝试了两天了一直实现不了，您有时间的话能发布一个带放大缩小功能的使用方法吗，万分感谢！ 
![image](https://user-images.githubusercontent.com/65274665/83121499-f1fc3400-a104-11ea-8994-7d650085b4a1.png)

**Comment by ssthouse** [comment]
@1063573718 hi, 缩放功能其实是在规划中的，只是工作比较忙所以搁置了。

大致的实现思路是： 监听鼠标滚轮事件，给svg节点和dom节点设置 `transform: scale()`来控制缩放

如果你有空的话，可以尝试实现下，提个PR；

**Comment by ssthouse** [comment]
@1063573718 hello, 放大缩小的接口加上了， 具体使用方法可以看这里：

[https://github.com/ssthouse/vue-tree-chart/blob/master/src/components/VueTreeDemo.vue](https://github.com/ssthouse/vue-tree-chart/blob/master/src/components/VueTreeDemo.vue)
