### ISSUE TITLE
折线图

### ISSUE THREAD

**Issue by pandly** [ssthouse/vue-tree-chart#12]
作者，你写的demo，可以改成折线图吗？改动的成本大不大？

**Comment by ssthouse** [comment]
折线图大概是什么效果哈，方便给个示意图不

**Comment by pandly** [comment]
[http://blog.zubasoft.at/Examples/D3.js/OrgChart/index.htm](url) 类似这样的

**Comment by pandly** [comment]
[http://blog.zubasoft.at/Examples/D3.js/OrgChart/index.htm](http://blog.zubasoft.at/Examples/D3.js/OrgChart/index.htm) 类似这样

**Comment by ssthouse** [comment]
试了下效果还行，我加个参数用来配置link的样式吧，下周一更新~

![image](https://user-images.githubusercontent.com/10973821/85130898-5d4ea700-b268-11ea-99c2-8c92054e82a5.png)

**Comment by pandly** [comment]
> 试了下效果还行，我加个参数用来配置link的样式吧，下周一更新~
> 
> ![image](https://user-images.githubusercontent.com/10973821/85130898-5d4ea700-b268-11ea-99c2-8c92054e82a5.png)

好的，谢谢

**Comment by ssthouse** [comment]
已经更新了，版本号 0.3.1

使用方法见： [https://github.com/ssthouse/vue-tree-chart#4-api](https://github.com/ssthouse/vue-tree-chart#4-api)
