### ISSUE TITLE
this.$refs.scaleTree.zoomOut is not a function

### ISSUE THREAD

**Issue by wmo123** [ssthouse/vue-tree-chart#14]
when i want to handle zoomout or zoomin, it casts 'this.$refs.scaleTree.zoomOut is not a function', why?

**Comment by wrkyle** [comment]
Did you ever figure out how to zoom on the tree chart?

**Comment by wrkyle** [comment]
@wmo123 It turns out that the current build in library/vue-tree-chart.js is a build of older code not the current code with the zoom functionality. @ssthouse just needs to run webpack on the current code to update the build. Then you should be able to use the zoom functionality.

**Comment by ssthouse** [comment]
hi, I have published a new version `0.4.3`, and write a simple demo to verify it:
[https://codesandbox.io/s/wispy-water-x65ct?file=/src/App.vue](https://codesandbox.io/s/wispy-water-x65ct?file=/src/App.vue)

The zoom API should be working now.
