### ISSUE TITLE
Demo shows zooming but no way to do so.

### ISSUE THREAD

**Issue by wrkyle** [ssthouse/vue-tree-chart#18]
I noticed your demo shows zooming functionality on the SVG renderer however there is no method provided in the documentation to do so. I really like this component.

**Comment by ssthouse** [comment]
hi，the zoom function showcase is placed at the bottom of the page

https://user-images.githubusercontent.com/10973821/108652154-6c27e080-74fe-11eb-837d-f6988992090d.mov


The zoom API is not documented in the readme file (my bad), you can check this demo function first, I'll add the document later~

[https://github.com/ssthouse/vue-tree-chart/blob/6f87bc272ea67d2198909f17a2193e0d67048cae/src/components/VueTreeDemo.vue#L200](https://github.com/ssthouse/vue-tree-chart/blob/6f87bc272ea67d2198909f17a2193e0d67048cae/src/components/VueTreeDemo.vue#L200)

**Comment by wrkyle** [comment]
Hi, thanks for your reply. I noticed the zoom code was in release v0.4.2 so I installed via npm
```
npm install --save git+https://github.com/ssthouse/vue-tree-chart.git#v0.4.2
```
When I look in the node_modules folder I see the new code with the zoomIn() and zoomOut() methods. However, the code being run in my app is still the old code without the zoom methods. Do you know why this is?

**Comment by wrkyle** [comment]
@ssthouse I think what's needed is a new webpack build of the updated code. Would you be willing to make a new release?

**Comment by ssthouse** [comment]
sure, a new version is released. see: #14
