### ISSUE TITLE
Zoom methods don't zoom on the current center.

### ISSUE THREAD

**Issue by wrkyle** [ssthouse/vue-tree-chart#19]
Hi again,

I notice both in the demo and in my application that the zoom methods don't zoom on the current center.

I think it would be more natural for the zoom to be centered on the current view. I tried making some modifications using transform-origin on the svg and domContainer but wasn't able to make much progress. If you could give me some guidance I could try and make the changes and create a pull request.

**Comment by wrkyle** [comment]
I managed to figure this out and have created a [pull request](https://github.com/ssthouse/vue-tree-chart/pull/20).

**Comment by ssthouse** [comment]
Nice job, I have merged the code and released version `0.4.4` 👏👏👏
