### ISSUE TITLE
Cannot import the VueTree component in TypeScript project

### ISSUE THREAD

**Issue by noneedinmagic** [ssthouse/vue-tree-chart#24]
It just gives me an error:

```
ERROR in %project%/client/src/apps/office/components/hierarchy/HierarchyTree.vue(7,21):
7:21 Could not find a declaration file for module '@ssthouse/vue-tree-chart'. '%project%/client/node_modules/@ssthouse/vue-tree-chart/library/vue-tree-chart.js' implicitly has an 'any' type.
  Try `npm install @types/ssthouse__vue-tree-chart` if it exists or add a new declaration (.d.ts) file containing `declare module '@ssthouse/vue-tree-chart';`
```

I've tried to create a `shims-vue-tree-chart.d.ts` file inside the `src` dir of my Vue project, but it didn't help. Two variants of its contents, both not working:

```
declare module '@ssthouse/vue-tree-chart';
```
and
```
import { VueConstructor } from 'vue';
declare module '@ssthouse/vue-tree-chart' {
  export = VueConstructor;
}
```

**Comment by ssthouse** [comment]
hi, I add a default type declaration file in version `0.4.5`, please check.

I'll add full typescript support later(maybe this month)

**Comment by solvntech** [comment]
Error when importing into vue3
<img width="716" alt="image" src="https://user-images.githubusercontent.com/107427084/216787980-475dd460-c8f8-4696-88b5-2d47c496500c.png">
