### ISSUE TITLE
Add feature for a node to have more than 1 parent

### ISSUE THREAD

**Issue by Maxim-Durand** [ssthouse/vue-tree-chart#31]
Hello,
I would love to use you library to build a tree where a child node could have different parent nodes, just like in the image bellow.

![tree](https://user-images.githubusercontent.com/72691393/116002011-14355500-a5e7-11eb-8221-77ca830378ff.PNG)

**Comment by ssthouse** [comment]
Hi, this seems like a good feature. But I can not spare time for it recently ;(

PR is very welcomed if you got time to develop this feature🌹

**Comment by ssthouse** [comment]
@Maxim-Durand thanks for your contribution👏

I have released this new feature in `0.5.2`, please check
