### ISSUE TITLE
Child to loop back to a parent and links styling.

### ISSUE THREAD

**Issue by DineshKarri443** [ssthouse/vue-tree-chart#33]
Hi, @ssthouse  , great library. I was taking a look at it and I was wondering if there is a way to loop back to a parent ? @Maxim-Durand  made a great contribution for connecting multiple childs to parents. But is there a way for a child to loop back to a grand parent or a great grand parent.  Any inputs would be of great help to me. Is this even feasible ? Below is an example of what I want to achieve. 

2. Also is there a possibility to either emit a link clicked event , or add a slot to click, style and add text to links  ? That would be great.  

![image](https://user-images.githubusercontent.com/68352790/119249639-ce54b800-bbb7-11eb-9acb-44c881aa0da8.png)

![image](https://user-images.githubusercontent.com/68352790/119259445-01b13a00-bbec-11eb-9400-12434c2bbd47.png)

**Comment by ssthouse** [comment]
> 1. if there is a way to loop back to a parent ?

hi, the chart's UI layout is powered by `d3.tree` and I didn't see any d3.tree demo that can link the child back to the parent.
We may need further investigation 🤔 


> 2. Also is there a possibility to either emit a link clicked event , or add a slot to click, style and add text to links ? That would be great.

this feature looks pretty cool, I'll try to implement this, but it may take some time, any PR is very welcomed!

**Comment by DineshKarri443** [comment]
@ssthouse  thanks for your response. Even I am not sure if linking pack to a grand paren is possible in a tree style.  

Regarding point 2 - I am very new to d3, nevertheless, I will try and see if I can contribute something. 
I set up my initial codesandbox to replicate your repo. 

I ran into an issue as soon as I added a link hover property.  I just added the link hover property to highlight a link when it is hovered. But I observed that only the links in the left-half of the chart are being highlighted. The hover action on the right-half is not working. Do you know any reason why this might be happening? 

I just added a simple hover pseudo-selector to the link tag and changed it to color "red" .   You can replicate it in the codesandbox below: 

https://codesandbox.io/s/loving-lake-3e6p8?file=/src/components/treeview.vue 

![image](https://user-images.githubusercontent.com/68352790/120834909-468c8780-c581-11eb-84e1-cb335f777ab4.png)
