### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by EHadoux** [ssthouse/vue-tree-chart#37]
Hello,

it looks like the component is not compatible with Vue 3. 
The errors reported are apparently quite common for components that are not compatible:
1. `Property "$createElement" was accessed during render but is not defined on instance.`
2. `Property "_self" was accessed during render but is not defined on instance.`

I'm not really sure what triggers them but it looks like doing stuff like 
```typescript
const self = this;
```
might be part of the issue.

I'd be happy to have a go but I might need some guidance if you know already.

**Comment by jamols09** [comment]
@ssthouse  please make it compatible with vue 3. This is one is the best tree view I've seen.

**Comment by kosirm** [comment]
+1 for vue3 compatibility. please!

**Comment by natenolting** [comment]
Does anyone know of a fork that has applied support for Vue 3?

**Comment by ssthouse** [comment]
I'm working on this, hope the vue3 version can be released before December;

**Comment by ssthouse** [comment]
@EHadoux @kosirm @natenolting @jamols09 
Hi all, the vue3 version is released:

```shell
npm i @ssthouse/vue3-tree-chart
```

the usage is slightly different the vue2 version, you can check this codesandbox example:
[codesandbox](https://codesandbox.io/s/vue3-tree-chart-demo-j11uj?file=/src/main.js)

I'll complete the vue3 version's document latter.

**Comment by EHadoux** [comment]
Amazing, cheers for that!
