### ISSUE TITLE
Zoom using scroll ( mouse wheel event  )

### ISSUE THREAD

**Issue by DineshKarri443** [ssthouse/vue-tree-chart#39]
@ssthouse  Thanks for this repo once again. 

Is there a way to add zoom in and zoom out on "mouse wheel scroll" . Most of the examples in the d3 library use d3's zoom event. 

Do you have an idea how we can enable zoom with mouse scroll?

**Comment by DineshKarri443** [comment]
@ssthouse  Could you please provide any inputs for me ? I've tried achieving it in multiple ways but some or the other thing breaks. This is an important criteria for me, but looks like I am stuck.

**Comment by ssthouse** [comment]
@DineshKarri443 Hi, sorry for the late reply~

You can listen to `mousewhell` event on dom node then call the `zoomIn()` and `zoomOut()` API.
