### ISSUE TITLE
Move using touch events?

### ISSUE THREAD

**Issue by SetcKe** [ssthouse/vue-tree-chart#54]
Thank you very much for this wonderful library.
Just wondering Is there any possible way to navigate the chart using touch events so that I can use it on my phone/tablet?

**Comment by ssthouse** [comment]
@SetcKe Hi, I test the demo page on my mobile phone(Android system) and it seems like the touch events are already supported.

demo page: [https://ssthouse.github.io/vue-tree-chart/#/svgTree](https://ssthouse.github.io/vue-tree-chart/#/svgTree)

You can try with your cell phone~

**Comment by SetcKe** [comment]
@ssthouse Hello! Thanks for the reply.
Yes, I agree that the touch/tap events are already working. However, the sweeping/touchmove event is not working for me to navigate around the chart if the tree is too large.

**Comment by dummydamn** [comment]
Can we reopen this issue? since i have a same problem as well

Or somehow did you solve this issue by your self? @SetcKe
